// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"database/sql"

	"github.com/google/uuid"
)

type Task struct {
	ID        uuid.UUID    `json:"id"`
	Title     string       `json:"title"`
	Completed bool         `json:"completed"`
	CreatedAt sql.NullTime `json:"created_at"`
}
